-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.audit_logs (
  id bigint NOT NULL DEFAULT nextval('audit_logs_id_seq'::regclass),
  user_id uuid,
  action character varying NOT NULL,
  entity_type character varying,
  entity_id uuid,
  ip_address character varying,
  user_agent text,
  details jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.bus_owners (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  company_name character varying NOT NULL,
  license_number character varying UNIQUE,
  contact_person character varying,
  address text,
  city character varying,
  state character varying,
  country character varying DEFAULT 'Sri Lanka'::character varying,
  postal_code character varying,
  verification_status USER-DEFINED DEFAULT 'pending'::verification_status,
  verification_documents jsonb,
  business_email character varying,
  business_phone character varying,
  tax_id character varying,
  bank_account_details jsonb,
  total_buses integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bus_owners_pkey PRIMARY KEY (id),
  CONSTRAINT bus_owners_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.bus_staff (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  bus_owner_id uuid,
  staff_type USER-DEFINED NOT NULL,
  license_number character varying,
  license_expiry_date date,
  license_document_url text,
  experience_years integer DEFAULT 0,
  emergency_contact character varying,
  emergency_contact_name character varying,
  medical_certificate_expiry date,
  medical_certificate_url text,
  background_check_status USER-DEFINED DEFAULT 'pending'::background_check_status,
  background_check_document_url text,
  employment_status USER-DEFINED DEFAULT 'pending'::employment_status,
  hire_date date,
  termination_date date,
  salary_amount numeric,
  performance_rating numeric DEFAULT 5.00 CHECK (performance_rating >= 0.00 AND performance_rating <= 5.00),
  total_trips_completed integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  profile_completed boolean DEFAULT false,
  verification_notes text,
  verified_at timestamp with time zone,
  verified_by uuid,
  CONSTRAINT bus_staff_pkey PRIMARY KEY (id),
  CONSTRAINT bus_staff_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT bus_staff_bus_owner_id_fkey FOREIGN KEY (bus_owner_id) REFERENCES public.bus_owners(id),
  CONSTRAINT bus_staff_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.users(id)
);
CREATE TABLE public.lounge_owners (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  business_name character varying NOT NULL,
  business_license character varying UNIQUE,
  contact_person character varying,
  business_address text,
  city character varying,
  state character varying,
  country character varying DEFAULT 'Sri Lanka'::character varying,
  postal_code character varying,
  verification_status USER-DEFINED DEFAULT 'pending'::verification_status,
  verification_documents jsonb,
  business_email character varying,
  business_phone character varying,
  tax_id character varying,
  bank_account_details jsonb,
  total_lounges integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lounge_owners_pkey PRIMARY KEY (id),
  CONSTRAINT lounge_owners_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.otp_rate_limits (
  id integer NOT NULL DEFAULT nextval('otp_rate_limits_id_seq'::regclass),
  identifier character varying NOT NULL,
  identifier_type character varying NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT otp_rate_limits_pkey PRIMARY KEY (id)
);
CREATE TABLE public.otp_verifications (
  id integer NOT NULL DEFAULT nextval('otp_verifications_id_seq'::regclass),
  phone character varying NOT NULL,
  otp_code character varying NOT NULL,
  purpose character varying DEFAULT 'login'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone NOT NULL,
  verified boolean DEFAULT false,
  verified_at timestamp with time zone,
  attempts integer DEFAULT 0,
  max_attempts integer DEFAULT 3,
  ip_address character varying,
  user_agent text,
  CONSTRAINT otp_verifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.refresh_tokens (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  token_hash character varying NOT NULL UNIQUE,
  device_id character varying,
  device_type USER-DEFINED,
  ip_address character varying,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone NOT NULL,
  last_used_at timestamp with time zone,
  revoked boolean DEFAULT false,
  revoked_at timestamp with time zone,
  CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  device_id character varying NOT NULL,
  device_type USER-DEFINED NOT NULL,
  device_model character varying,
  app_version character varying,
  os_version character varying,
  fcm_token character varying,
  ip_address character varying,
  location_permission boolean DEFAULT false,
  notification_permission boolean DEFAULT false,
  last_activity_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  phone character varying NOT NULL UNIQUE,
  email character varying UNIQUE,
  first_name character varying,
  last_name character varying,
  nic character varying UNIQUE,
  date_of_birth date,
  address text,
  city character varying,
  postal_code character varying,
  roles ARRAY DEFAULT ARRAY['passenger'::text],
  profile_photo_url text,
  profile_completed boolean DEFAULT false,
  status USER-DEFINED DEFAULT 'pending'::user_status,
  phone_verified boolean DEFAULT false,
  email_verified boolean DEFAULT false,
  last_login_at timestamp with time zone,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id)
);