-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.active_trips (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  scheduled_trip_id uuid NOT NULL,
  bus_id uuid NOT NULL,
  permit_id uuid NOT NULL,
  driver_id uuid NOT NULL,
  conductor_id uuid,
  current_latitude numeric,
  current_longitude numeric,
  last_location_update timestamp with time zone,
  current_speed_kmh numeric,
  heading numeric,
  current_stop_id uuid,
  next_stop_id uuid,
  stops_completed ARRAY,
  actual_departure_time timestamp with time zone,
  estimated_arrival_time timestamp with time zone,
  actual_arrival_time timestamp with time zone,
  status character varying NOT NULL DEFAULT 'not_started'::character varying CHECK (status::text = ANY (ARRAY['not_started'::character varying, 'in_transit'::character varying, 'at_stop'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])),
  current_passenger_count integer DEFAULT 0,
  tracking_device_id character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT active_trips_pkey PRIMARY KEY (id),
  CONSTRAINT active_trips_scheduled_trip_id_fkey FOREIGN KEY (scheduled_trip_id) REFERENCES public.scheduled_trips(id),
  CONSTRAINT active_trips_bus_id_fkey FOREIGN KEY (bus_id) REFERENCES public.buses(id),
  CONSTRAINT active_trips_permit_id_fkey FOREIGN KEY (permit_id) REFERENCES public.route_permits(id),
  CONSTRAINT active_trips_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.bus_staff(id),
  CONSTRAINT active_trips_conductor_id_fkey FOREIGN KEY (conductor_id) REFERENCES public.bus_staff(id),
  CONSTRAINT active_trips_current_stop_id_fkey FOREIGN KEY (current_stop_id) REFERENCES public.master_route_stops(id),
  CONSTRAINT active_trips_next_stop_id_fkey FOREIGN KEY (next_stop_id) REFERENCES public.master_route_stops(id)
);
CREATE TABLE public.audit_logs (
  id bigint NOT NULL DEFAULT nextval('audit_logs_id_seq'::regclass),
  user_id uuid,
  action character varying NOT NULL,
  entity_type character varying,
  entity_id uuid,
  ip_address character varying,
  user_agent text,
  details jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.bookings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  scheduled_trip_id uuid NOT NULL,
  user_id uuid NOT NULL,
  booking_reference character varying NOT NULL UNIQUE,
  number_of_seats integer NOT NULL CHECK (number_of_seats > 0),
  boarding_stop_id uuid,
  alighting_stop_id uuid,
  total_fare numeric NOT NULL,
  payment_status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (payment_status::text = ANY (ARRAY['pending'::character varying, 'paid'::character varying, 'failed'::character varying, 'refunded'::character varying]::text[])),
  payment_method character varying,
  payment_reference character varying,
  paid_at timestamp with time zone,
  booking_status character varying NOT NULL DEFAULT 'confirmed'::character varying CHECK (booking_status::text = ANY (ARRAY['confirmed'::character varying, 'cancelled'::character varying, 'completed'::character varying, 'no_show'::character varying]::text[])),
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  passenger_name character varying,
  passenger_phone character varying,
  passenger_email character varying,
  special_requests text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bookings_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_scheduled_trip_id_fkey FOREIGN KEY (scheduled_trip_id) REFERENCES public.scheduled_trips(id),
  CONSTRAINT bookings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT bookings_boarding_stop_id_fkey FOREIGN KEY (boarding_stop_id) REFERENCES public.master_route_stops(id),
  CONSTRAINT bookings_alighting_stop_id_fkey FOREIGN KEY (alighting_stop_id) REFERENCES public.master_route_stops(id)
);
CREATE TABLE public.bus_owner_routes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  bus_owner_id uuid NOT NULL,
  master_route_id uuid NOT NULL,
  custom_route_name character varying NOT NULL,
  direction character varying NOT NULL CHECK (direction::text = ANY (ARRAY['UP'::character varying, 'DOWN'::character varying]::text[])),
  selected_stop_ids ARRAY NOT NULL CHECK (array_length(selected_stop_ids, 1) >= 2),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bus_owner_routes_pkey PRIMARY KEY (id),
  CONSTRAINT fk_bus_owner_routes_master_route FOREIGN KEY (master_route_id) REFERENCES public.master_routes(id),
  CONSTRAINT fk_bus_owner_routes_bus_owner FOREIGN KEY (bus_owner_id) REFERENCES public.bus_owners(id)
);
CREATE TABLE public.bus_owners (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  company_name character varying,
  license_number character varying UNIQUE,
  contact_person character varying,
  address text,
  city character varying,
  state character varying,
  country character varying DEFAULT 'Sri Lanka'::character varying,
  postal_code character varying,
  verification_status USER-DEFINED DEFAULT 'pending'::verification_status,
  verification_documents jsonb,
  business_email character varying,
  business_phone character varying,
  tax_id character varying,
  bank_account_details jsonb,
  total_buses integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  profile_completed boolean DEFAULT false,
  identity_or_incorporation_no character varying,
  CONSTRAINT bus_owners_pkey PRIMARY KEY (id),
  CONSTRAINT bus_owners_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.bus_staff (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  bus_owner_id uuid,
  staff_type USER-DEFINED NOT NULL,
  license_number character varying,
  license_expiry_date date,
  license_document_url text,
  experience_years integer DEFAULT 0,
  emergency_contact character varying,
  emergency_contact_name character varying,
  medical_certificate_expiry date,
  medical_certificate_url text,
  background_check_status USER-DEFINED DEFAULT 'pending'::background_check_status,
  background_check_document_url text,
  employment_status USER-DEFINED DEFAULT 'pending'::employment_status,
  hire_date date,
  termination_date date,
  salary_amount numeric,
  performance_rating numeric DEFAULT 5.00 CHECK (performance_rating >= 0.00 AND performance_rating <= 5.00),
  total_trips_completed integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  profile_completed boolean DEFAULT false,
  verification_notes text,
  verified_at timestamp with time zone,
  verified_by uuid,
  CONSTRAINT bus_staff_pkey PRIMARY KEY (id),
  CONSTRAINT bus_staff_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT bus_staff_bus_owner_id_fkey FOREIGN KEY (bus_owner_id) REFERENCES public.bus_owners(id),
  CONSTRAINT bus_staff_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.users(id)
);
CREATE TABLE public.buses (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  bus_owner_id uuid NOT NULL,
  permit_id uuid NOT NULL,
  bus_number character varying NOT NULL,
  license_plate character varying NOT NULL UNIQUE,
  bus_type character varying NOT NULL CHECK (bus_type::text = ANY (ARRAY['normal'::character varying, 'luxury'::character varying, 'semi_luxury'::character varying, 'super_luxury'::character varying]::text[])),
  total_seats integer NOT NULL CHECK (total_seats > 0),
  manufacturing_year integer CHECK (manufacturing_year >= 1900 AND manufacturing_year::numeric <= (EXTRACT(year FROM CURRENT_DATE) + 1::numeric)),
  last_maintenance_date date,
  insurance_expiry date,
  status character varying NOT NULL DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'maintenance'::character varying, 'inactive'::character varying]::text[])),
  has_wifi boolean NOT NULL DEFAULT false,
  has_ac boolean NOT NULL DEFAULT false,
  has_charging_ports boolean NOT NULL DEFAULT false,
  has_entertainment boolean NOT NULL DEFAULT false,
  has_refreshments boolean NOT NULL DEFAULT false,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT buses_pkey PRIMARY KEY (id),
  CONSTRAINT fk_bus_owner FOREIGN KEY (bus_owner_id) REFERENCES public.bus_owners(id),
  CONSTRAINT fk_permit FOREIGN KEY (permit_id) REFERENCES public.route_permits(id)
);
CREATE TABLE public.lounge_owners (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  business_name character varying,
  business_license character varying,
  manager_full_name character varying,
  manager_nic_number character varying,
  manager_email character varying,
  manager_nic_front_url text,
  manager_nic_back_url text,
  registration_step character varying DEFAULT 'phone_verified'::character varying,
  profile_completed boolean DEFAULT false,
  verification_status character varying DEFAULT 'pending'::character varying,
  verification_notes text,
  verified_at timestamp with time zone,
  verified_by uuid,
  total_lounges integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  total_staff integer DEFAULT 0,
  CONSTRAINT lounge_owners_pkey PRIMARY KEY (id),
  CONSTRAINT lounge_owners_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT lounge_owners_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.users(id)
);
CREATE TABLE public.lounge_staff (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  lounge_id uuid NOT NULL,
  user_id uuid,
  phone_number character varying NOT NULL,
  full_name character varying,
  nic_number character varying,
  nic_front_url text,
  nic_back_url text,
  email character varying,
  permission_type character varying DEFAULT 'staff'::character varying,
  employment_status character varying DEFAULT 'pending'::character varying,
  hired_date date,
  terminated_date date,
  has_registered boolean DEFAULT false,
  invited_at timestamp with time zone DEFAULT now(),
  registered_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lounge_staff_pkey PRIMARY KEY (id),
  CONSTRAINT lounge_staff_lounge_id_fkey FOREIGN KEY (lounge_id) REFERENCES public.lounges(id),
  CONSTRAINT lounge_staff_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.lounges (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  lounge_owner_id uuid NOT NULL,
  lounge_name character varying NOT NULL,
  description text,
  address text NOT NULL,
  city character varying NOT NULL,
  state character varying DEFAULT 'Western'::character varying,
  country character varying DEFAULT 'Sri Lanka'::character varying,
  postal_code character varying,
  latitude numeric,
  longitude numeric,
  contact_phone character varying,
  price_1_hour numeric,
  price_2_hours numeric,
  price_until_bus numeric,
  amenities jsonb DEFAULT '[]'::jsonb,
  images jsonb DEFAULT '[]'::jsonb,
  status character varying DEFAULT 'pending'::character varying,
  is_operational boolean DEFAULT true,
  total_staff integer DEFAULT 0,
  average_rating numeric DEFAULT 0.00,
  total_bookings integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lounges_pkey PRIMARY KEY (id),
  CONSTRAINT lounges_lounge_owner_id_fkey FOREIGN KEY (lounge_owner_id) REFERENCES public.lounge_owners(id)
);
CREATE TABLE public.master_route_stops (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  master_route_id uuid NOT NULL,
  stop_name character varying NOT NULL,
  stop_order integer NOT NULL,
  latitude numeric,
  longitude numeric,
  arrival_time_offset_minutes integer,
  is_major_stop boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT master_route_stops_pkey PRIMARY KEY (id),
  CONSTRAINT master_route_stops_master_route_id_fkey FOREIGN KEY (master_route_id) REFERENCES public.master_routes(id)
);
CREATE TABLE public.master_routes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  route_number character varying NOT NULL UNIQUE,
  route_name character varying NOT NULL,
  origin_city character varying NOT NULL,
  destination_city character varying NOT NULL,
  total_distance_km numeric,
  estimated_duration_minutes integer,
  encoded_polyline text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT master_routes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.otp_rate_limits (
  id integer NOT NULL DEFAULT nextval('otp_rate_limits_id_seq'::regclass),
  identifier character varying NOT NULL,
  identifier_type character varying NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT otp_rate_limits_pkey PRIMARY KEY (id)
);
CREATE TABLE public.otp_verifications (
  id integer NOT NULL DEFAULT nextval('otp_verifications_id_seq'::regclass),
  phone character varying NOT NULL,
  otp_code character varying NOT NULL,
  purpose character varying DEFAULT 'login'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone NOT NULL,
  verified boolean DEFAULT false,
  verified_at timestamp with time zone,
  attempts integer DEFAULT 0,
  max_attempts integer DEFAULT 3,
  ip_address character varying,
  user_agent text,
  CONSTRAINT otp_verifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.refresh_tokens (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  token_hash character varying NOT NULL UNIQUE,
  device_id character varying,
  device_type USER-DEFINED,
  ip_address character varying,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone NOT NULL,
  last_used_at timestamp with time zone,
  revoked boolean DEFAULT false,
  revoked_at timestamp with time zone,
  CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.route_permits (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  bus_owner_id uuid NOT NULL,
  permit_number character varying NOT NULL,
  bus_registration_number character varying NOT NULL,
  via ARRAY,
  approved_fare numeric NOT NULL CHECK (approved_fare > 0::numeric),
  issue_date date NOT NULL,
  expiry_date date NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::verification_status,
  verification_documents jsonb,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  master_route_id uuid NOT NULL,
  permit_type character varying DEFAULT 'regular'::character varying,
  max_trips_per_day integer,
  allowed_bus_types ARRAY,
  restrictions text,
  verified_at timestamp with time zone,
  permit_document_url text,
  approved_seating_capacity integer CHECK (approved_seating_capacity IS NULL OR approved_seating_capacity > 0),
  CONSTRAINT route_permits_pkey PRIMARY KEY (id),
  CONSTRAINT route_permits_bus_owner_id_fkey FOREIGN KEY (bus_owner_id) REFERENCES public.bus_owners(id),
  CONSTRAINT route_permits_master_route_id_fkey FOREIGN KEY (master_route_id) REFERENCES public.master_routes(id)
);
CREATE TABLE public.scheduled_trips (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  trip_schedule_id uuid,
  permit_id uuid,
  trip_date date NOT NULL,
  departure_time time without time zone NOT NULL,
  estimated_arrival_time time without time zone,
  assigned_driver_id uuid,
  assigned_conductor_id uuid,
  is_bookable boolean DEFAULT false,
  base_fare numeric,
  status character varying NOT NULL DEFAULT 'scheduled'::character varying CHECK (status::text = ANY (ARRAY['scheduled'::character varying, 'confirmed'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])),
  cancellation_reason text,
  cancelled_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  assignment_deadline timestamp with time zone,
  CONSTRAINT scheduled_trips_pkey PRIMARY KEY (id),
  CONSTRAINT scheduled_trips_trip_schedule_id_fkey FOREIGN KEY (trip_schedule_id) REFERENCES public.trip_schedules(id),
  CONSTRAINT scheduled_trips_permit_id_fkey FOREIGN KEY (permit_id) REFERENCES public.route_permits(id),
  CONSTRAINT scheduled_trips_assigned_driver_id_fkey FOREIGN KEY (assigned_driver_id) REFERENCES public.bus_staff(id),
  CONSTRAINT scheduled_trips_assigned_conductor_id_fkey FOREIGN KEY (assigned_conductor_id) REFERENCES public.bus_staff(id)
);
CREATE TABLE public.system_settings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  setting_key character varying NOT NULL UNIQUE,
  setting_value text NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT system_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.trip_schedules (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  bus_owner_id uuid NOT NULL,
  schedule_name character varying,
  recurrence_type character varying NOT NULL CHECK (recurrence_type::text = ANY (ARRAY['daily'::character varying, 'weekly'::character varying, 'interval'::character varying]::text[])),
  recurrence_days ARRAY,
  specific_dates ARRAY,
  departure_time time without time zone NOT NULL,
  base_fare numeric NOT NULL CHECK (base_fare > 0::numeric),
  is_active boolean DEFAULT true,
  valid_from date,
  valid_until date,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  estimated_arrival_time time without time zone,
  recurrence_interval integer CHECK (recurrence_interval IS NULL OR recurrence_interval > 0),
  bus_owner_route_id uuid,
  CONSTRAINT trip_schedules_pkey PRIMARY KEY (id),
  CONSTRAINT trip_schedules_bus_owner_id_fkey FOREIGN KEY (bus_owner_id) REFERENCES public.bus_owners(id),
  CONSTRAINT fk_trip_schedules_bus_owner_route FOREIGN KEY (bus_owner_route_id) REFERENCES public.bus_owner_routes(id)
);
CREATE TABLE public.user_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  device_id character varying NOT NULL,
  device_type USER-DEFINED NOT NULL,
  device_model character varying,
  app_version character varying,
  os_version character varying,
  fcm_token character varying,
  ip_address character varying,
  location_permission boolean DEFAULT false,
  notification_permission boolean DEFAULT false,
  last_activity_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  phone character varying NOT NULL UNIQUE,
  email character varying UNIQUE,
  first_name character varying,
  last_name character varying,
  nic character varying UNIQUE,
  date_of_birth date,
  address text,
  city character varying,
  postal_code character varying,
  roles ARRAY DEFAULT ARRAY['passenger'::text],
  profile_photo_url text,
  profile_completed boolean DEFAULT false,
  status USER-DEFINED DEFAULT 'pending'::user_status,
  phone_verified boolean DEFAULT false,
  email_verified boolean DEFAULT false,
  last_login_at timestamp with time zone,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id)
);